### ISSUE TITLE
Home page > Mobile > Menu > Nav links not working

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#101]
## Is your feature request related to a problem? Please describe.
On mobile devices, the nav menu options do not take the user to the desired section.

## Describe the solution you'd like
Apply the same changes to the mobile nav that were applied to the desktop nav and the footer

**Comment by Kingrashy12** [comment]
I would like to work on this issue

**Comment by kylescudder** [comment]
Hi @Kingrashy12 any movement on this? This is quite urgent for use to launch the site when we want. Are you able to do this before the end of the year?
