### ISSUE TITLE
Tailwindcss > Extend colours > Add error, success and alert from Primitive Tokens V1.0.0

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#114]
## Is your feature request related to a problem? Please describe.
The primitive token colours added by Kyle in the Figma boards need to be added to the tailwindcss config so we can use then for our base components and class variables.

## Describe the solution you'd like
Extend the existing colour profiles in tailwindcss config file to include the 3 colour profiles in the Primitive tokens v1.0. figma board.

## Screenshots

If you do not have access to the figma board, these are the colours we should be adding:
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/0c2b1da5-bec7-41fd-9c99-be2de0180e5a)

**Comment by vinaybhamre** [comment]
Hey @kylescudder 
Can I work on this?

**Comment by kylescudder** [comment]
Hi @vinaybhamre we would be thrilled if you would like to contribute to the project! 

If you have any questions, or think our documentation could be clearer, we are just starting out, so any feedback you could give us would be greatly appreciated.
