### ISSUE TITLE
Mobile layout > FAQs > subheader does have have appropriate margin

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#122]
## Describe the bug
The subheader for FAQs currently fills the full width of the screen. 

## To Reproduce
1. Go to home page
2. Scroll down to FAQs
4. See subheader with incorrect margin

## Expected behavior
The subheader margin should match the figma design

## Screenshots
Desired design:
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/c2157798-d6e6-43e5-b753-4a1e9fbbf580)

Current design:
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/6a769bc3-f7b2-48d2-96d6-935370f152cc)

**Comment by s3822042** [comment]
I can work on this
