### ISSUE TITLE
Mobile layout > Team > subheader does have have appropriate margin

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#123]
## Describe the bug
The subheader for Team currently fills the full width of the screen. 

## To Reproduce
1. Go to home page
2. Scroll down to Team
4. See subheader with incorrect margin

## Expected behavior
The subheader margin should match the figma design

## Screenshots
Desired design:
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/820f264b-b8c7-4efd-8d8b-199097a8862d)

Current design:
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/80ba0f9c-b22a-4968-85b8-750edad3fbec)

**Comment by s3822042** [comment]
I can work on this
