### ISSUE TITLE
Mobile layout > Project > Text margin and font size don't correspond to desired design

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#124]
## Describe the bug
The subheader for project currently has too large of a margin to the top of the section. Additionally, the font size is too small.

## To Reproduce
1. Go to home page
2. Scroll down to project
4. See subheader with incorrect top margin

## Expected behavior
The subheader margin should match the figma design. Additionally, the font size should match the font size of the mission section.

## Screenshots
Desired design:
<img width="480" alt="image" src="https://github.com/StudyCrew/StudyCrew/assets/105601287/04e63706-3bdd-452c-be4a-e27ccc08d938">

Current design:
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/a7dc2eac-f3d6-4f34-b8da-f0e3e50f6456)

**Comment by jeffmancilla** [comment]
happy to work on this one @JacobHeldt. i presume this involves styling using tailwind classes as well?

**Comment by JacobHeldt** [comment]
That sounds great! Yes, could you please implement your changes using Tailwind and update the current CSS in the Project component to Tailwind within this issue? We would appreciate it, as we are aiming to convert everything to Tailwind. However, we would also approve a pull request with the CSS changes and create a separate issue for converting it to Tailwind later. Thank you!
