### ISSUE TITLE
Mobile layout > Features > Mobile design needs entire overhaul

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#125]
## Describe the bug
The features section has not been designed to work on mobile devices.

## To Reproduce
1. Go to home page
2. Scroll down to Features
4. See the section in it's current non-responsive design

## Expected behavior
The subheader margin should match the figma design

## Screenshots
Desired design:
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/6c32e5a3-6e81-4e44-8dc8-a5adc90a5a9e)

Current design:
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/78d4e265-1bde-4a6d-a600-e458696613e7)

**Comment by vishalbhati123** [comment]
Hey there, I'm activity working on this to find a solution, Thanks I'll let you know on the updates on this.

**Comment by f3rno64** [comment]
@JacobHeldt I'm handling this one.
