### ISSUE TITLE
R&D > File Uploading > Cost analysis for blob storage

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#133]
Research into what different free or low cost file hosting options exist that can be used for the study group file uploading.

These options need to ideally be free, or at a low cost to start with, with the option to scale later as needed.

**Comment by vishalbhati123** [comment]
I can work on this

**Comment by f3rno64** [comment]
@kylescudder I use **[Bytescale](https://www.bytescale.com/)** on my personal projects, and it's amazing. The pricing is also great. What do you think? The API is also a pleasure to work with.
