### ISSUE TITLE
R&D > Real-time chat > Cost analysis for real-time chat service

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#134]
Research into what different free or low cost real-time chat options exist that can be used for the study group messaging.

These options need to ideally be free, or at a low cost to start with, with the option to scale later as needed.

## Additional note

Socket.io could be [used](https://betterprogramming.pub/socket-io-and-nextjs-build-real-time-chat-application-part-1-976555ecba)

**Comment by vishalbhati123** [comment]
I can work on this

**Comment by f3rno64** [comment]
@JacobHeldt, Ideally, we should spin up a small dedicated VPS on Google Cloud for this and run a socket.io server on it. It would be much cheaper than any 3rd party solution.
