### ISSUE TITLE
Homepage > Mission > Update mission statement

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#140]
## Describe the bug
There are typos in the mission statement. Additionally, the mission statement can be shortened to make it clearer.
## Expected behavior
The text on the mission statement should be the following:
> StudyCrew is committed to make education more accessible, collaborative, and engaging through innovative learning platforms. Our vision is to provide every student with the resources and community they need to reach their full potential.

**Comment by hamzambo** [comment]
Hello. I would love on it. Thanks.

**Comment by hamzambo** [comment]
Hello. I would like to work on it.

**Comment by vimal20002** [comment]
I have dealt with similar issues on my personal projects .Assign this to me , you won't be disappointed !

**Comment by JacobHeldt** [comment]
> I have dealt with similar issues on my personal projects .Assign this to me , you won't be disappointed !
I have assigned the issue to you. Can you create the pull request by tomorrow?

**Comment by JacobHeldt** [comment]
> Hello. I would like to work on it.

Hello @hamzambo! Thank you for expressing an interest in helping out. However, I would like to let you know that I did not assign this particular issue to you. If you are still interested in contributing, you can take a look at the following issues: #124, #123, and #122. Please let me know if you are willing to tackle any of these issues."

**Comment by vimal20002** [comment]
I have raised a PR for same please review and merge it. @JacobHeldt

**Comment by JacobHeldt** [comment]
> I have raised a PR for same please review and merge it. @JacobHeldt
Thank you!
