### ISSUE TITLE
Homepage > Footer > Update footer design and content on desktop

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#158]
## Is your feature request related to a problem? Please describe.
We would like to expand the content of our footer and update the design accordingly."
## Describe the solution you'd like
Please update the footer to match the design displayed in the attached screenshot. 
## Screenshot
**Current Design**
<img width="1428" alt="Screenshot 2024-01-10 at 9 05 15 PM" src="https://github.com/StudyCrew/StudyCrew/assets/105601287/fc1188b7-d225-4a9e-8dfe-013e271edca7">
**Desired Design**
![Screenshot 2024-01-10 at 9 06 00 PM](https://github.com/StudyCrew/StudyCrew/assets/105601287/9674ebc6-1ef6-4c28-b1e4-23b76fdf0cf3)
## Content
If you would like to contribute to this task, please leave a comment and we will provide you with the necessary links to complete the pull request.

**Comment by f3rno64** [comment]
I'm working on this.
