### ISSUE TITLE
Component > Base > Textarea > Create

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#170]
## Is your feature request related to a problem? Please describe.
In order for us to build out the project in the quickest and most efficient manner, and to ensure that new features are consistent, we need a library of base components that we can use throughout the project.

## Describe the solution you'd like
Create an textarea component using the following structure:

Component should be created in the following directory - `component/ui/[componentName]`

It should be comprised of the following elements
* `types.ts` - type/interface definitions, such as `ComponentProps`
* `props.ts` - exports `propTypes` and `defaultProps`
* `index.tsx` - the component itself
* `style.scss` - optional as we will use tailwindcss, but if needed it should be created and imported in `index.tsx`

The component should be created using the shadcn-ui library, these will give you a string starting point. To create the new component use the following command:
```bash
npx shadcn-ui@latest add [component]
```
To see a list of shadcn-ui components please refer to the [documentation](https://ui.shadcn.com/docs/components).

Please follow the design as specified in this [Figma file](https://www.figma.com/file/8ofD0vh1MC8US8gvwZFpqG/StudyCrew-Development-Prototypes?type=design&node-id=102%3A417&mode=design&t=XLGd0gBWKe9eHIkb-1). The text box component is on the Components page.

**Comment by s3822042** [comment]
I can work on this

**Comment by s3822042** [comment]
<img width="1347" alt="Screenshot 2024-04-07 at 20 56 50" src="https://github.com/StudyCrew/StudyCrew/assets/62096559/4dd5ba20-229b-4eec-b34f-4b1b1262cd03">

The component is already created, so this issue is no longer valid, unless we want to change something

**Comment by JacobHeldt** [comment]
Hi @s3822042 ! The current file does not match the specifications outlined in the Figma file. Could you please revise the existing file to align with the design detailed in our Figma file? The link can be found in the issue. Thank you!

**Comment by s3822042** [comment]
Hi @JacobHeldt , I believe this is design for the textarea, if so I created this PR to align with that design
<img width="936" alt="Screenshot 2024-06-15 at 15 03 26" src="https://github.com/StudyCrew/StudyCrew/assets/62096559/fb2a11f4-eb03-4ea9-9ee2-b35d63317bb5">

**Comment by JacobHeldt** [comment]
Thank you for your message @s3822042 ! Zai created a PR that updated the components to match the designs, which was merged yesterday.
