### ISSUE TITLE
Linting > Resolve outstanding linting issues

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#185]
## Describe the bug
There are a number of linting issues in the project that need to be resolved.

## To Reproduce
1. Run `pnpm lint` and see the outstanding linting issues.

## Expected behavior
`pnpm lint` should return no linting issues.

**Comment by f3rno64** [comment]
This is done courtesy of https://github.com/StudyCrew/StudyCrew/pull/196
