### ISSUE TITLE
Homepage > Setup Google Analytics

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#194]
## Describe the Problem
We do not have a method of tracking the number of visitors to our website.
## Expected behavior
Google Analytics should be installed on every page of our website immediately after the `<head>` element with this code:
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-X2C2PEWH0E"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-X2C2PEWH0E');
</script>
```

**Comment by f3rno64** [comment]
I'll implement this.
