### ISSUE TITLE
Homepage > Waitlist > Add confirmation message

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#200]
## Is your feature request related to a problem? Please describe.
Currently, users do not receive a confirmation message when they join the waitlist.
## Describe the solution you'd like
After the user clicks the "Join Waitlist" button, a card should appear with the following content:
- "Thank you for joining the StudyCrew waitlist!"
- "We'll keep you updated on your waitlist status and inform you as soon as access is available"
- "Find us on"
  - "@studycrewofficial"
  - "@studycrew.world"
The desired design is shown in this gif
![Waitlist Video](https://github.com/StudyCrew/StudyCrew/assets/105601287/5998c962-6690-4bc1-8141-a31e326423af)
<img width="745" alt="image" src="https://github.com/StudyCrew/StudyCrew/assets/105601287/5f88b65f-4c8e-4460-97e7-fb1646e853e7">

The social media icons can be downloaded from https://phosphoricons.com/

**Comment by zaibutcooler** [comment]
I will work on this,
