### ISSUE TITLE
Component > General Refactor

### ISSUE THREAD

**Issue by f3rno64** [StudyCrew/StudyCrew#203]
Some components follow bad practices, like defining methods without `useCallback` in the component root and using them in the component JSX. This issue represents a general refactoring task touching all components. Unnecessary comments should also be removed.

**Comment by kylescudder** [comment]
Now the other branch has been merged in, you should be okay to rebase this one and carry on with it.

**Comment by f3rno64** [comment]
I'm closing this as it is too broad; I will open multiple smaller issues outlining specific tasks to achieve the same result.
