### ISSUE TITLE
Homepage > Add Privacy Policy

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#234]
## Why
We don't have a privacy policy yet
## Task
Implement the completed privacy policy content on our website. It should be accessible via a dedicated route, preferably www.studycrew.world/privacy-policy.
## Requirements
- Once assigned this issue, please request the privacy policy content from us.
- Ensure the policy is displayed clearly and is easily navigable from the website's main menu or footer.
- Test for accessibility and mobile responsiveness.

**Comment by vishalbhati123** [comment]
I can work on this

**Comment by abiel13** [comment]
Would love to work on this

**Comment by f3rno64** [comment]
@abiel13 do you still want to work on this?

**Comment by zaibutcooler** [comment]
working on it!
