### ISSUE TITLE
Homepage > Waitlist > Minimum Age Requirement

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#240]
## Why
Our waitlist should only be open to individuals, who are 16 years of age or older. 
## Task
Implement a confirmation box in the waitlist section and the join waitlist option on the footer. If that box is not checked, the user should not be able to join the waitlist, but an error message should show, like in the design.
### Waitlist section:
Confirmation box 

<img width="528" alt="Screenshot 2024-01-29 at 7 16 36 PM" src="https://github.com/StudyCrew/StudyCrew/assets/105601287/4b7d6ab8-b085-4990-8ec4-4e41dcf7490a">

Checked confirmation box 

<img width="528" alt="Screenshot 2024-01-29 at 7 17 10 PM" src="https://github.com/StudyCrew/StudyCrew/assets/105601287/555a498c-bba4-493a-8577-ddcfad0363a2">

Error when confirmation box is not checked

<img width="528" alt="Screenshot 2024-01-29 at 7 17 50 PM" src="https://github.com/StudyCrew/StudyCrew/assets/105601287/b8332cde-9ade-4701-936b-9715dad21627">

---

### Footer:
Confirmation box 

<img width="711" alt="Screenshot 2024-01-29 at 7 24 24 PM" src="https://github.com/StudyCrew/StudyCrew/assets/105601287/970ba9d6-a1ba-4ce3-aa21-d1815b82c638">

Checked confirmation box

<img width="669" alt="Screenshot 2024-01-29 at 7 24 50 PM" src="https://github.com/StudyCrew/StudyCrew/assets/105601287/0c253049-39d8-418c-b08e-d627fe389305">

Error when confirmation box is not checked

<img width="669" alt="Screenshot 2024-01-29 at 7 25 18 PM" src="https://github.com/StudyCrew/StudyCrew/assets/105601287/9ce2f16f-494d-448b-ad2e-99d8e59039d0">

**Comment by f3rno64** [comment]
@JacobHeldt I'm working on this now.
