### ISSUE TITLE
General > Use Tailwind CSS

### ISSUE THREAD

**Issue by f3rno64** [StudyCrew/StudyCrew#244]
We need to replace all stylesheets and use **[TailwindCSS](https://tailwindcss.com/)** exclusively. To accomplish this, remove **all** stylesheet files and inline styles, and add the matching tailwind classes to the affected components.

**Comment by f3rno64** [comment]
I'd like to work on this, so I've assigned the issue to myself.

**Comment by abiel13** [comment]
would love to work on this
