### ISSUE TITLE
Homepage > Team > Avatars not showing

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#285]
## Is your feature request related to a problem? Please describe.
On the homepage, the avatars are not showing in the team members section.
<img width="1278" alt="Screenshot 2024-03-28 at 12 51 16 PM" src="https://github.com/StudyCrew/StudyCrew/assets/105601287/f0430d38-ba3d-496e-b086-84f04d5d1fe0">

## Describe the solution you'd like
Ensure that the avatars (svg files) show for every team member.

**Comment by zaibutcooler** [comment]
I will check the issue

**Comment by cvalencia1991** [comment]
hello @JacobHeldt could you please assign me to me

**Comment by cvalencia1991** [comment]
this issue can be close
