### ISSUE TITLE
Homepage > Horizontal Overflow

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#296]
## Describe the bug
There is an overflow on the right side of the homepage on desktop resolutions, as shown in this screenshot:
<img width="1383" alt="Screenshot 2024-04-05 at 9 11 58 AM" src="https://github.com/StudyCrew/StudyCrew/assets/105601287/274535a1-b6a8-42e9-9595-cbe0c0502fc8">

## Expected behavior
The homepage should not have any overflow to the right.

**Comment by shanrasool** [comment]
hey can I help fix this issue

**Comment by JacobHeldt** [comment]
Hey @shanrasool! Sorry, pull request was already created for this issue. Thank you for having a look at our repo, feel free to comment on other issues you'd like to work on. We would greatly appreciate your contributions!
