### ISSUE TITLE
Fonts > add Rubik as a font in Tailwind config

### ISSUE THREAD

**Issue by jeffmancilla** [StudyCrew/StudyCrew#309]
**Is your feature request related to a problem? Please describe.**
currently there isn't a tailwind class to change font to Rubik (per [design system](https://www.figma.com/file/Y7kX0ZhQSXqldqx1GLdVaT/StudyCrew-Prototypes?type=design&node-id=1205-431&mode=design&t=Xk2MEbmmqNqRvcvN-0), heading `font-family` should be set to Rubik)

**Describe the solution you'd like**
- a new *tailwind class* for setting an element's `font-family` to *Rubik*. If:
  - *DM Sans* and *Rubik* are the only two fonts declared according to the design system, and
  - DM Sans = sans & Rubik = serif, then:
  - it might make sense to override the `sans` and `serif` tailwind font families with the respective fonts:
```js
module.exports = {
  theme: {
    fontFamily: {
      'sans': ['DM Sans', 'ui-sans-serif', 'system-ui'],
      'serif': ['Rubik', 'ui-serif'],
    },
  },
}
```
(above code is loosely based on Tailwind's docs)

**Describe alternatives you've considered**
- in the `@layer base` of the project's main css, add a selector for h1-h6 with a `font-family: 'Rubik'` rule. this removes needing to explicitly add the tailwind class on headings, at the cost of flexibility
 
**Additional context**
- this issue seems related to #2

**Comment by cvalencia1991** [comment]
hello @JacobHeldt  could you please assign me to me
