### ISSUE TITLE
Fonts > Resolve Font Configuration Conflicts 

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#313]
## Problem
There are ongoing conflicts between direct `font-family` CSS properties and Tailwind's `font-sans` utility classes. These conflicts prevent Tailwind from correctly applying the DM Sans font as specified in the global Tailwind configuration.
## Expected Behavior
All text elements across the aplication should consistently use the DM Sans of the Rubik font font as specified in Tailwind's configuration without being overridden by other CSS rules. The use fonts directly imported from external sources such as Google Fonts should be avoided.
## Possible solutions
- Implement  Tailwind's `@layer` directives to ensure that Tailwind's styles have higher specificity than CSS.
- Remove any direct `font-family` declarations that conflict with Tailwind's settings from the CSS files

**Comment by jeffmancilla** [comment]
happy to work on this!
