### ISSUE TITLE
Homepage > Features > Update Features Section

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#317]
## Problem
The features section includes features that are not planned anymore or too broad to be displayed. These should be more focused on what we plan to implement in the near future.
## Solution
The features for stage one should only include:
- Study Groups
- Tutoring
- Learning Paths
- Personal Dashboard
- User Profile

This means: **Remove the gamification and feedback forum cards**.

The features for stage two should only include: 
- Mobile Application
- AI Tutor
- Notes
- Flashcards
- Multilingual support

This means: **Remove the messaging and courses cards**

The features for stage three should only include:
- Courses (The description can be found in the features card that currently is in stage 2)
- Virtual Events
- "More Features based on User Feedback" (Description: We will incorporate your feedback in stage three to introduce new features that make education more accessible, collaborative, and engaging.)

This means: **Remove all cards except the Virtual Events card and add a Courses and User Feedback card**

**Comment by zaibutcooler** [comment]
I would love to work on this
