### ISSUE TITLE
Component > Styling > Footer > Replace CSS with tailwindcss

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#32]
## Is your feature request related to a problem? Please describe.
We have decided we want to use tailwindcss in this project, and not vanilla CSS, so the footer component needs migrating.

## Describe the solution you'd like
Migrate the current contents of `Footer.css` to tailwindcss in `Footer.tsx` and delete the `Footer.css`

**Comment by abiel13** [comment]
would love to work on this
