### ISSUE TITLE
Homepage > Styling > Remove Unnecessary CSS Files

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#332]
## Describe the problem
There are CSS files in component folders that are already converted to Tailwind.

## Expected behavior
Unused CSS files in the project should be deleted. For instance, there is a CSS file in the project component that is no longer necessary since the styling has already been replaced with Tailwind. Therefore, the CSS file in the project component should be deleted. The same applies to other components of the homepage where unused CSS files are present.

**Comment by thepug432** [comment]
[This](https://github.com/StudyCrew/StudyCrew/pull/372) should fix the issue, note only 1 file seems to be unnecessary at the moment.
