### ISSUE TITLE
Homepage > Temporarily Remove Waitlist Functionality

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#334]
## Description
We had waitlist functionality on our homepage, both as a separate section and as part of the footer. However, we have decided to temporarily remove both of these sections. Our focus now is on developing the platform functionality, and once significant progress is made, we will re-implement the waitlist functionality as currently shown on the homepage. This will ensure that there is not a significant delay between joining the waitlist and testing the platform, which reduces the risk of losing users who have signed up to the waitlist. When updating the footer, the collaborations column with its elements can be removed as well, as this is no longer relevant.

## Tasks
- Disable all waitlist frontend components.
- Disable all waitlist backend components.
- Remove collaborations column from footer.
- Ensure that website continues to run smoothly and vercel preview can be built.

**Comment by cvalencia1991** [comment]
assign me to me @JacobHeldt please

**Comment by franclobo** [comment]
I'll take this issue
