### ISSUE TITLE
Homepage > Disable Clerk

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#335]
## Issue
Since we won't need Clerk for now, disable the usage of Clerk for our homepage. This will make compliance with cookie policies easier. 

## Expected Behavior
Clerk should be removed from all components so that no cookies are being collected by Clerk.

**Comment by career-tokens** [comment]
I can do this . Now there is an update by clerk where all the routes are by default public and you need to mention the private ones. Should I opt for changing middleware.ts and keep all routes public or simply remove all clerk related stuff

**Comment by JacobHeldt** [comment]
You can remove all the clerk related stuff for now, we'll implement it later with the updates.
