### ISSUE TITLE
Component > Base > Checkbox > Create

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#338]
## Is your feature request related to a problem? Please describe.
In order for us to build out the project in the quickest and most efficient manner, and to ensure that new features are consistent, we need a library of base components that we can use throughout the project.
## Describe the solution you'd like
Create an input component using the following structure:

Component should be created in the following directory - `component/ui/[componentName]`

It should be comprised of the following elements

`types.ts` - type/interface definitions, such as ComponentProps
`props.ts` - exports propTypes and defaultProps
`index.tsx`- the component itself
`style.scss `- optional as we will use tailwindcss, but if needed it should be created and imported in index.tsx
The component should be created using the shadcn-ui library, these will give you a string starting point. To create the new component use the following command:
```
npx shadcn-ui@latest add [component]
```
To see a list of shadcn-ui components please refer to the [documentation](https://ui.shadcn.com/docs/components).

As the design of the component is not yet finalised, do not worry about the styling at this time. These components need to exist so we can start building out the PoT.
##
Additional context
Please follow the design as specified in this [Figma file](https://www.figma.com/design/8ofD0vh1MC8US8gvwZFpqG/StudyCrew-Development-Prototypes?node-id=102%3A417&t=7i0cOnAtFAEeW2tx-1). Navigate the the Components page and then have a look at the Checkbox component.

**Comment by career-tokens** [comment]
May I pick that up?

**Comment by JacobHeldt** [comment]
For sure, thank you for contributing to our repo @career-tokens! Yes, you can leave the other files as they are and focus on the files specified in this prompt. As you mentioned, shadcn will also be used as a starting point for this component, but please ensure that the design of the component corresponds exactly to the design specified in our figma file.

**Comment by JacobHeldt** [comment]
This was implemented in a larger PR a few days ago.
