### ISSUE TITLE
Component > Styling > Mission > Replace CSS with tailwindcss

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#35]
## Is your feature request related to a problem? Please describe.
We have decided we want to use tailwindcss in this project, and not vanilla CSS, so the mission component needs migrating.

## Describe the solution you'd like
Migrate the current contents of `Mission.css` to tailwindcss in `Mission.tsx` and delete the `Mission.css`

**Comment by jeffmancilla** [comment]
may i work on this?

**Comment by cvalencia1991** [comment]
i can Work on this

**Comment by cvalencia1991** [comment]
Please Delete this issue
