### ISSUE TITLE
General > Update All Dependencies

### ISSUE THREAD

**Issue by zahtec** [StudyCrew/StudyCrew#350]
Update all packages to their latest versions and repair any broken or deprecated code; this will ensure we are employing the latest each platform and framework has to offer. Such updating is still a relatively small issue due to the codebases’ small size, hence we should do it now before developing several pages and/or complex backend infrastructure.

**Comment by zaibutcooler** [comment]
I think I have already updated the necessary packages in my previous commit (depreciated ones). I will
