### ISSUE TITLE
General > Update pnpm Lockfile and Delete package Lockfile

### ISSUE THREAD

**Issue by zahtec** [StudyCrew/StudyCrew#351]
The latest `pnpm` lockfile version is `9.0`; this repository uses version `6.0`. The newest version should be migrated to since any newer version of pnpm will be unable to read the lockfile otherwise (not great on `pnpm`'s part but yeah). This issues ties in well with https://github.com/StudyCrew/StudyCrew/issues/350 as by updating all packages, there is no need to conserve the old lockfile contents.

**Comment by zaibutcooler** [comment]
updated the depreciated dependencies in my latest pr (safe to close the issue after my pr)
