### ISSUE TITLE
General > Create Contributing Tutorial

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#361]
## Create a Detailed Guideline for Contributing to Our Project
We need a comprehensive guideline to help new contributors understand how to contribute to our project. The guide should assume that the reader is completely new to open source. Please include detailed instructions for each step of the contributing process.

## Steps to Include:
Commenting on Issues:
- How to find and select an issue to work on.
- How to add a comment so we can assign the issue

Forking the Repository:
- Step-by-step instructions on how to fork the repository to their own GitHub account.
Creating Branches:
- How to create a new branch for their work.
- Naming conventions for branches.
Setting Up the Project Locally:
- Detailed setup guide for getting the project up and running on their local machine.

Making Changes:
- Best practices for coding and making changes.
Creating Pull Requests (PRs):
- Step-by-step guide on how to create a pull request.
- What to include in the PR description.
- Guidelines for addressing review comments.

Additional Information:
- Any additional steps that are necessary for contributing
- Technologies that we use
- Links to additional resources, such as coding standards, documentation, and project-specific guidelines.
- Contact information or how to seek help if they get stuck.
## Adding the Guide:
Once the guide is complete, add it to our repository as a markdown file named `HOW_TO_CONTRIBUTE.md`.

**Comment by zaibutcooler** [comment]
If no one is actively working on it, I will work on it!

**Comment by JacobHeldt** [comment]
> If no one is actively working on it, I will work on it!

Awesome, thank you! I just assigned the issue.
