### ISSUE TITLE
General > Website Not Indexed in Google

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#365]
## Description
Our website is currently not indexed by Google, and we are encountering several errors in the Google Search Console. The specific issues reported are as follows:
- Server error (5xx) for the https://www.studycrew.world/ page.
- Excluded by ‘noindex’ tag for the https://studycrew.world/, http://www.studycrew.world/, and http://studycrew.world/ pages.

## Steps to Resolve
- Thoroughly scan the codebase to identify any potential issues causing the 5xx server errors.
- Check the server configuration and logs to pinpoint any server-side problems.
- Verify that all dependencies are correctly installed and configured.
- Inspect the code to ensure no noindex tags are unintentionally applied to any pages.

If no issues are found within the code, this might indicate a problem with the domain configurations.

## Reporting
Findings and updates can be reported in the following ways:
- Direct message on Discord (@.___jacob___)
- Comment on this issue
- Creating a separate issue to address specific problems identified

**Comment by zahtec** [comment]
- Noindex on those pages is fine, those are redirects
- Tested https://www.studycrew.world/ with pagespeed insights, which is a service by Google, and it was able to properly crawl the site. The 500 error may be an old issue and the site likely needs a re-index request.

**Comment by JacobHeldt** [comment]
Thank you for your comment! Unfortunately, after reindexing the websites, these errors persist.
<img width="712" alt="Screenshot 2024-07-24 at 8 48 38 PM" src="https://github.com/user-attachments/assets/d2f59ff0-5ca3-41c5-adc2-bb33893237ae">

**Comment by zahtec** [comment]
The validation is still in its "started" phase, meaning they have not actually done anything. Maybe try contacting support at this point.

**Comment by franclobo** [comment]
Hello, @JacobHeldt !
I would like to suggest creating a `sitemap.xml` file in the public directory, as follows:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="styles.css" ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">
<url>
<loc>https://www.studycrew.world/</loc>
<lastmod>2023-10-09T11:07:00-05:00</lastmod>
<changefreq>monthly</changefreq>
<priority>1.0</priority>
</url>
<url>
  <loc>https://studycrew.world//</loc>
  <lastmod>2023-10-09T11:07:00-05:00</lastmod>
  <changefreq>monthly</changefreq>
  <priority>0.8</priority>
</url>
<url>
  <loc>http://www.studycrew.world/</loc>
  <lastmod>2023-10-09T11:07:00-05:00</lastmod>
  <changefreq>monthly</changefreq>
  <priority>0.8</priority>
</url>
</urlset>
```

**Comment by franclobo** [comment]
Also, you will need to create a new file in the public directory `robots.txt` as follows:

```txt
User-agent: *
Disallow: /_next/static/media
Disallow: /favicon.ico

Sitemap: https://studycrew.world/sitemap.xml  # Ruta al archivo sitemap XML
```
