### ISSUE TITLE
Linting Rules Too Strict Causing Errors

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#366]
## Description:
Several developers have reported difficulties with the current linting rules, which are overly strict and cause errors during contributions. This issue requires a comprehensive analysis of our linting configuration.

## Tasks:
- Analyze the existing linting rules and identify problematic areas.
- Develop a plan to adjust the linting rules for better flexibility without compromising code quality.
- Submit the plan to me (.___jacob___) on Discord for approval.
- Upon approval, create new issues to implement the changes.

## Outcome:
A more developer-friendly linting setup that maintains code quality and reduces contribution errors.

**Comment by zaibutcooler** [comment]
I will work on this Issue.
