### ISSUE TITLE
Component > Styling > Navbar > Replace CSS with tailwindcss

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#37]
## Is your feature request related to a problem? Please describe.
We have decided we want to use tailwindcss in this project, and not vanilla CSS, so the navbar component needs migrating.

## Describe the solution you'd like
Migrate the current contents of `Navbar.css` to tailwindcss in `Navbar.tsx` and delete the `Navbar.css`

**Comment by thepug432** [comment]
Could this be assigned to me?

**Comment by JacobHeldt** [comment]
> Could this be assigned to me?

For sure, thank you @thepug432 !

**Comment by thepug432** [comment]
PR created.
