### ISSUE TITLE
Components > Remove Tooltip Folder

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#370]
## Description:
Currently, our project structure contains a duplicate Tooltip component within the src/components directory. This is causing redundancy and potential confusion. Specifically:
- Most of our components, including tooltip.tsx, are correctly placed in the src/components/ui folder.
- Additionally, there exists a Tooltip folder within the src/components directory that needs to be removed.
## Task
Please remove the Tooltip folder from the src/components directory to ensure consistency and clarity in our project structure.

**Comment by Tapudp** [comment]
Hi @JacobHeldt , I have aimed to resolve this issue in the following PR : https://github.com/StudyCrew/StudyCrew/pull/371

Please let me know if there are more changes or items that requires the attention to be reviewed.

I am looking forward to contribute to the project actively.

**Comment by JacobHeldt** [comment]
Thank you very much for working on this @Tapudp ! I just merged your PR. Looking forward to collaborating with you!
