### ISSUE TITLE
General > Plan and Reorganize Folder Structure for StudyCrew Platform Development

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#375]
## Objective
We need to plan and organize the folder structure for the development of our actual StudyCrew platform. The current repo primarily focuses on the homepage, but we aim to develop the platform separately. This issue involves making suggestions for reorganizing the current folder structure to accommodate both the homepage and the platform development.

## Tasks
**Assess Current Folder Structure**
- Review the existing folder structure of the repository.
- Identify files and folders related to the homepage and separate them from the platform development.

**Plan the New Folder Structure**
- Propose a new folder structure that supports the development of the StudyCrew platform. Add folders that will be needed for the platform.
- Ensure the new structure clearly distinguishes between the homepage and platform (currently we have both homepage components and platform components in our `src/components` folder).

## Additional Information
- Refer to our Figma file to see how the basic version of our platform with the folder structure should look: [StudyCrew Prototype](https://www.figma.com/design/1Z1NIZIPE7TTqQXM7xk8av/StudyCrew-Prototype?node-id=0-1&t=Z9IkwDMiY2hQ63sL-1).
- Create a comprehensive document detailing the proposed folder structure.
- Include a brief description of the purpose of each folder and key files within them.
- Share the proposed folder structure plan with the team for feedback.
- Message me (@.___jacob___) on Discord if you have any questions or need further clarification.
- Once approved, add the plan as a markdown file to this repo.

**Comment by zaibutcooler** [comment]
Could you make a list of the future routes and the features so that we can adjust the file structures based on the routes and the api endpoints?? That would make a lot more sense to reorganize things.

**Comment by JacobHeldt** [comment]
> Could you make a list of the future routes and the features so that we can adjust the file structures based on the routes and the api endpoints?? That would make a lot more sense to reorganize things.

Sure, that makes sense @zaibutcooler . A general over view is in the Figma prototype that I've linked on the issue. We also have this issue #373 for planning API endpoints.

**Comment by JacobHeldt** [comment]
> Okay I will work on both issues.

Awesome @zaibutcooler🔥!
