### ISSUE TITLE
Component > Styling > Project > Replace CSS with tailwindcss

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#38]
## Is your feature request related to a problem? Please describe.
We have decided we want to use tailwindcss in this project, and not vanilla CSS, so the project component needs migrating.

## Describe the solution you'd like
Migrate the current contents of `Project.css` to tailwindcss in `Project.tsx` and delete the `Project.css`

**Comment by Kingrashy12** [comment]
I would like to work on this issue

**Comment by jeffmancilla** [comment]
may i work on this? i did the majority of the work via another issue but i didn't delete the css as described here

**Comment by JacobHeldt** [comment]
Definitely! As you mentioned, most of the code already is in tailwind but the CSS file still has to be deleted.

**Comment by abiel13** [comment]
@JacobHeldt
