### ISSUE TITLE
Homepage > Navbar > Ensure that Navbar Remains Visible

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#384]
## Problem
The navbar on our homepage currently disappears when the user scrolls down. This can hinder navigation and user experience.
<img width="1438" alt="Screenshot 2024-06-17 at 5 01 27 PM" src="https://github.com/StudyCrew/StudyCrew/assets/105601287/5462478a-ec60-4403-b9a7-6c07aaa8a03f">

## Solution
The navbar should remain fixed at the top of the page, visible at all times, regardless of how far the user scrolls. Implement this using tailwindcss and ensure that the solution works across different browsers and devices.

**Comment by abiel13** [comment]
would love to work on this
