### ISSUE TITLE
Component > Styling > Signup > Replace CSS with tailwindcss

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#39]
## Is your feature request related to a problem? Please describe.
We have decided we want to use tailwindcss in this project, and not vanilla CSS, so the signup component needs migrating.

## Describe the solution you'd like
Migrate the current contents of `Signup.css` to tailwindcss in `Signup.tsx` and delete the `Signup.css`

**Comment by Kingrashy12** [comment]
I would like to work on this issue

**Comment by jeffmancilla** [comment]
may i work on this

**Comment by JacobHeldt** [comment]
Of coure, thank you @jeffmancilla ! Some parts of this component have already been implemented with a tailwind, but there are still a few parts where CSS is used.

**Comment by abiel13** [comment]
would love to work on this
