### ISSUE TITLE
Component > Styling > Team > Replace CSS with tailwindcss

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#40]
## Is your feature request related to a problem? Please describe.
We have decided we want to use tailwindcss in this project, and not vanilla CSS, so the team component needs migrating.

## Describe the solution you'd like
Migrate the current contents of `Team.css` to tailwindcss in `Team.tsx` and delete the `Team.css`

**Comment by Kingrashy12** [comment]
I would like to work on this issue

**Comment by cvalencia1991** [comment]
hello @JacobHeldt you can assign me to me

**Comment by abiel13** [comment]
would love to work on this
