### ISSUE TITLE
Remove Cookies From Homepage

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#415]
## Description:
We have identified two cookies on the homepage that should be removed. The cookies in question are highlighted in the attached screenshot.
<img width="1440" alt="image" src="https://github.com/StudyCrew/StudyCrew/assets/105601287/a021d35f-96e1-446e-ab0f-1f5855e07af9">

## Task:
- Locate the source of these cookies in the codebase.
- Remove the cookies if possible.

## Steps to Reproduce:
1. Navigate to the homepage.
2. Inspect the cookies to identify the ones shown in the screenshot.

## Expected Outcome:
The homepage should no longer set the identified cookies.

## Additional Information:
Please ensure to test the homepage functionality after removing the cookies to confirm that there are no adverse effects.

**Comment by thiagorabaioli** [comment]
Let's try!

**Comment by rayvego** [comment]
I am not able to reproduce this issue. However, upon research, this cookie appears if you have visited a website that uses Cloudflare. You can delete the cookie and try refreshing the page to see if you still get it.

**Comment by JacobHeldt** [comment]
> I am not able to reproduce this issue. However, upon research, this cookie appears if you have visited a website that uses Cloudflare. You can delete the cookie and try refreshing the page to see if you still get it.

Thank you @rayvego! It probably was my browser cache or something, the cookie doesn't show up anymore after deleting and refreshing the page. I'll close this issue.
