### ISSUE TITLE
Backend > Setup Supabase

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#427]
## Why
We want to use Supabase for authentication and data storage.

## Tasks
**Setup Supabase**
- Install Supabase
- Configure Supabase on frontend (create `supabaseClient.js` file) and backend

**Update Documentation**
- Update `.env.example`. These are the public variables for our mock database
```
NEXT_PUBLIC_SUPABASE_URL=https://iqbtyidkfhmqokxopxhf.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxYnR5aWRrZmhtcW9reG9weGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjA0NTI4NDgsImV4cCI6MjAzNjAyODg0OH0.eo6MVgRbXbdpdUlj4YQo4NJ6D0kE2HRQaLO4VOAOMd4
```
- Update `README.md`
- Update `CONTRIBUTING.md`

**Remove unnecessary components**
- Remove MongoDB from project entirely
- Remove Clerk from project entirely

**Comment by franclobo** [comment]
Challenge accepted! I want to implement Supabase, all helphands are welcome. I guess I will finish it in three weeks.
