### ISSUE TITLE
Backend > Integrate Supabase Authentication Backend Functionality

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#428]
## Description
We need to implement Supabase authentication for our project to manage user registration and login securely. This issue focuses solely on the backend integration of Supabase authentication, including setting up the necessary configuration and endpoints. The frontend integration will be handled in a separate issue.

## Tasks
- Implement endpoints for user registration, login, and logout using Supabase's authentication API
- Implement middleware to protect routes and ensure only authenticated users can access certain endpoints. The homepage should stay open to everyone though.
- Document processes and ensure security in handling user data.

**Comment by franclobo** [comment]
Challenge accepted! I want to implement Supabase, all helphands are welcome. I guess, I will finish it in three weeks.

**Comment by JacobHeldt** [comment]
Great, thank you @franclobo!
