### ISSUE TITLE
Frontend > Implement Supabase Authentication Frontend Functionality

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#429]
## Description
Following the implementation of the backend functionality for Supabase authentication, we need to integrate the authentication features into the frontend. This includes creating UI components for user registration, login, and onboarding. The designs and details on the avatar mechanism are defined in our [Figma file](https://www.figma.com/design/MdMR4stU8dWZitGYjOvcOi/StudyCrew-Onboarding?node-id=0-1&t=aqmK0wi7vNoB4nhz-1).
## Tasks
- Implement user firendly pages for registration, login, and onboarding as defined in our [Figma file](https://www.figma.com/design/MdMR4stU8dWZitGYjOvcOi/StudyCrew-Onboarding?node-id=0-1&t=aqmK0wi7vNoB4nhz-1).
- Connect the frontend components to the backend authentication endpoints.
- Ensure the application updates the UI based on the user's authentication state (e.g., showing/hiding protected routes).
- Ensure and document adequate security measures for authentication.

## Considerations
- Make sure that the design corresponds exactly to the designs that we have specified in the [Figma file](https://www.figma.com/design/MdMR4stU8dWZitGYjOvcOi/StudyCrew-Onboarding?node-id=0-1&t=aqmK0wi7vNoB4nhz-1).
- Ensure that the avatar creation functionality is implemented as specified in the [Figma file](https://www.figma.com/design/MdMR4stU8dWZitGYjOvcOi/StudyCrew-Onboarding?node-id=0-1&t=aqmK0wi7vNoB4nhz-1).
- Make sure that we can later easily update the "Our Features" section on the sign up page and the "Updates" section on the login page.
- Ensure that implementation of "Continue with Google" button corresponds to the [branding guidelines](https://developers.google.com/identity/branding-guidelines#:~:text=Use%20the%20Google%20brand%20color,%2C%20light%2C%20and%20neutral%20modes.&text=Use%20monochrome%20versions%20of%20the%20Google%20%22G%22%20for%20the%20button.&text=Choose%20the%20button%20in%20the,for%20accessibility%20and%20equal%20prominence.&text=Put%20the%20standard%20color%20Google,light%2C%20dark%2C%20or%20neutral.) of Google. The Supabase default may be used if it corresponds to these guidelines.
- Use variables from our `tailwind.config.ts` file instead of hard-coded values where possible.
- Integrate base components from `src/components/ui` where appropriate.

**Comment by franclobo** [comment]
Challenge accepted! I want to implement Supabase, all helphands are welcome. I guess, I will finish it in three weeks.

**Comment by JacobHeldt** [comment]
Awesome @franclobo! We are still working on the design for this component, so the other two issues related to Supabase have priority right now. I'll let you know when the design is done!
