### ISSUE TITLE
Styling > Landing > Replace CSS with tailwindcss

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#43]
## Is your feature request related to a problem? Please describe.
We have decided we want to use tailwindcss in this project, and not vanilla CSS, so the landing page style sheet needs migrating.

## Describe the solution you'd like
Migrate the current contents of `Landing.css` to tailwindcss in `[root]/page.tsx.tsx` and delete the `Landing.css`

**Comment by Kingrashy12** [comment]
I would like to work on this issue
