### ISSUE TITLE
General > Set Up Page Routes

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#431]
## Description
We need to set up the page routes for the first version of StudyCrew based on the plan documented in `docs/routes.md` and this [prototype](https://www.figma.com/design/1Z1NIZIPE7TTqQXM7xk8av/StudyCrew-Prototype?node-id=0-1&t=iaEzOlEwae6SsWKf-1) of our main functionality.
## Tasks
- Set up the boilerplate for each planned route as documented in routes.md.
- Ensure that the file structure follows Next.js conventions.
- Each page should have a basic component with placeholder text indicating its purpose.

**Comment by zaibutcooler** [comment]
I will continue this after planning api routes.
