### ISSUE TITLE
General > Finish Mock Database Implementation

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#443]
We have recently defined the basic tables of our mock database in Supabase according to the schema defined in `docs/schema.txt` (issue #386). We've also decided to implement the types through typesafe frontend functionality. These are the tasks that we still have to get done to finalize our mock database:
- Define currently missing types in the frontend app (as we decided to implement the types through typesafe frontend functionality).
- Populate the database with actual mock data. This data should mimick data that we will have on our platform, like the data defined in the examples section of `docs/schema.txt`.

**Comment by franclobo** [comment]
Let's do it. 😃
