### ISSUE TITLE
Implement Docker Compatibility

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#455]
## Description
Making our codebase docker compatible will be helpful for contributors as it more streamlined service management and mitigates conflicts with different package versions. This issue involves making sure our project can be used with Docker to implement this functionality.

## Tasks
- Create a Dockerfile to define the project's environment.
- Test condebase with Docker.
- Document the Docker setup and update documentation (for example `CONTRIBUTING.md` and `README.md`) for contributors.

**Comment by rayvego** [comment]
I would like to work on this feature!
