### ISSUE TITLE
Frontend > Study Groups > Design Group Card Component

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#460]
## Description
The [group card](https://www.figma.com/design/f7DDsNcrvIjTdx7K7GSSh9/Group-Card?node-id=1-1513&t=T7PgxR7ASfdPOiGt-1) component will be displayed on both the personal dashboard and the study group search page. This issue involves implementing the group card component in a new `src/components/widgets` directory. The data for the title, description, image, etc., will be fetched on the actual pages and passed to this component as props. This issue does not involve fetching data from our Supabase database, but should ensure the group card can receive data as props.

## Tasks
- Initialize a new file in the new `src/components/widgets` directory.
- Create the group card as specified in our [Figma design](https://www.figma.com/design/f7DDsNcrvIjTdx7K7GSSh9/Group-Card?node-id=1-1513&t=T7PgxR7ASfdPOiGt-1).

## Considerations
- Follow the design in our [Figma file](https://www.figma.com/design/f7DDsNcrvIjTdx7K7GSSh9/Group-Card?node-id=1-1513&t=T7PgxR7ASfdPOiGt-1) closely, including colors, padding, font sizes, margins, etc. (all styling should use Tailwind).
- Use variables instead of hard-coded values wherever possible. The variables are defined in tailwind.config.ts.
- Follow best practices and ensure proper documentation.
- Integrate base components, such as buttons, from the `src/components/ui` when reasonable.

**Comment by career-tokens** [comment]
working on this
