### ISSUE TITLE
Documentation > Update Database Schema Documentation

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#462]
## Description
While building our mock database, we made necessary adjustments to our database schema. These changes should be reflected in the `docs/schema.txt` file. This issue is to ensure the `schema.txt` file is updated to match our Supabase database schema exactly.

Please review the current schema in our Supabase database and update the schema.txt file accordingly. For access to our mock database, reach out to me on Discord. Ensure to add details such as whether a field is nullable or unique, which can be seen in the Supabase web interface.

If you have any questions, please feel free to reach out to me!

## Tasks
- Review the Supabase mock database schema.
- Update the `schema.txt` file to reflect the current schema.
- Ensure the example section of the `schema.txt` file is updated.
- Add additional details, including whether a field is nullable and if it has to be unique.

**Comment by franclobo** [comment]
I'll take it!
