### ISSUE TITLE
Frontend > Study Groups > Q&A > Create Question Component

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#463]
## Description
The [question component](https://www.figma.com/design/5uf2nsKxXSnOzZdlYCuzeR/Question-Component?node-id=0-1&t=dREUSsNUkMch4h8a-1) will be displayed on both the group overview page and the group Q&A page. This component shows important information about a question that the user posts - specifically the question title, the number of replies, the user who posted the question, the number of upvotes, and an upvote button. This issue involves implementing the question component in the new src/components/widgets directory. The data for the title, username, user avatar, number of replies, etc., will be fetched on the actual pages and passed to this component as props. This issue does not involve fetching data from our Supabase database, but should ensure that the question component can receive data as props.

## Tasks
- Initialize a new file in the `src/components/widgets` directory.
- Create the question component exactly as specified in our [Figma design](https://www.figma.com/design/5uf2nsKxXSnOzZdlYCuzeR/Question-Component?node-id=0-1&t=dREUSsNUkMch4h8a-1).

## Considerations 
- Follow the design in our [Figma file](https://www.figma.com/design/5uf2nsKxXSnOzZdlYCuzeR/Question-Component?node-id=0-1&t=dREUSsNUkMch4h8a-1) closely, including colors, padding, font sizes, margins, etc. (all styling should use Tailwind).
- Use variables instead of hard-coded values wherever possible. The variables are defined in tailwind.config.ts.
- Follow best practices and ensure proper documentation.
- Integrate base components, such as buttons, from the `src/components/ui` directory when reasonable.

**Comment by zaibutcooler** [comment]
will work on the issue
