### ISSUE TITLE
Frontend > Update Tailwind Variables

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#464]
## Description
Our current tailwind.config.ts file is missing several important color and text variables necessary for our platform. We need to update this file to include the required color variables (such as error, alert, blue, grey shades, and others) and text variables (which encompass font family, font weight, and font size). The specific variables can be found in our [Zeplin project](https://app.zeplin.io/project/6619c41abd3195a6618177f6).

## Tasks
- Review the color variables defined in the [Zeplin project](https://app.zeplin.io/project/6619c41abd3195a6618177f6).
- Update the tailwind.config.ts file to include all these color variables.
- Review the text variables defined in the [Zeplin project](https://app.zeplin.io/project/6619c41abd3195a6618177f6).
- Update the tailwind.config.ts file to include all these text variables.
- Update current code to match the new color and text variables.

## Considerations
- Follow best practices for configuring Tailwind CSS.
- Use clear and consistent naming conventions for the variables.
- Test the updated configuration to ensure it works as expected across different components and does not impact the design of our homepage.

**Comment by zaibutcooler** [comment]
Safe to close
