### ISSUE TITLE
Frontend > Widgets > Create Material Widget

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#468]
## Description
The [material component](https://www.figma.com/design/DNSXhaHlJmHPzAsqm5zmku/Material-Component?node-id=0-1&t=1aqP406bhoRCPO5m-1) should be displayed on both the group overview page and the groups material page. The design varies slightly between these use cases, so this issue involves implementing two different variants as specified in the [Figma file](https://www.figma.com/design/DNSXhaHlJmHPzAsqm5zmku/Material-Component?node-id=0-1&t=1aqP406bhoRCPO5m-1). The component should be flexible to determine the variant based on the context where it is used.

The implementation should be placed in a new `src/components/widgets` directory. The data for the title, link, user, date, etc., will be fetched on the actual pages and passed to this component as props. This issue does not involve fetching data from our Supabase database, but it should ensure the component can receive data as props. Each material has an associated type in our database, and the icon on the left of the material component should be determined by this type.

## Tasks
- Initialize a new file in the new src/components/widgets directory.
- Create the material component as specified in our [Figma design](https://www.figma.com/design/DNSXhaHlJmHPzAsqm5zmku/Material-Component?node-id=0-1&t=1aqP406bhoRCPO5m-1).
- Implement both design variants, ensuring that the variant to display can be determined by the page context.
- Ensure that the icon is determined by the material type, which will be passed as a prop.

## Considerations
- Follow the design in our [Figma file](https://www.figma.com/design/DNSXhaHlJmHPzAsqm5zmku/Material-Component?node-id=0-1&t=1aqP406bhoRCPO5m-1) closely, including colors, padding, font sizes, margins, etc. All styling should use Tailwind CSS.
- Use variables defined in tailwind.config.ts instead of hard-coded values wherever possible.
- Follow best practices and ensure proper documentation.
Integrate base components from the `src/components/ui` directory when reasonable.

**Comment by rayvego** [comment]
Hey, I'd like to work on this.
