### ISSUE TITLE
Frontend > Widgets > Implement Filter Tag Widget

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#469]
## Description
The [filter tag component](https://www.figma.com/design/fBDxFJwNOBXmoL7gdw0FNT/Filter-Widget?node-id=0-1&t=ugQ81USLdLPAdRnp-1) will be displayed on the page for searching groups and will be used on additional pages in the future. These tags are part of a filter system. As shown in our [Figma file](https://www.figma.com/design/fBDxFJwNOBXmoL7gdw0FNT/Filter-Widget?node-id=0-1&t=ugQ81USLdLPAdRnp-1), users can click on these tags to activate a filter on a page. This issue involves implementing the filter tag component in the new src/components/widgets directory. The data for the icon and text will be passed to this component as props from the actual page.

## Tasks
- Initialize a new file in the `src/components/widgets` directory.
- Create the filter tag component exactly as specified in our [Figma design](https://www.figma.com/design/fBDxFJwNOBXmoL7gdw0FNT/Filter-Widget?node-id=0-1&t=ugQ81USLdLPAdRnp-1).

## Considerations
- Follow the design in our [Figma file](https://www.figma.com/design/fBDxFJwNOBXmoL7gdw0FNT/Filter-Widget?node-id=0-1&t=ugQ81USLdLPAdRnp-1) closely, including colors, padding, font sizes, margins, etc. All styling should use Tailwind CSS.
- Use variables defined in `tailwind.config.ts` instead of hard-coded values wherever possible.
- Follow best practices and ensure proper documentation.
- Integrate base components, such as buttons, from the src/components/ui directory when reasonable.

**Comment by rayvego** [comment]
Hey, I'd like to work on this as well.
