### ISSUE TITLE
Frontend > Widgets > Create Chat Message Widget

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#470]
## Description
The [chat message widget](https://www.figma.com/design/uP10Fb7SRKo1R1wOTEPLcd/Chat-Widget?node-id=0-1&t=sVG4VXBH5Fn8jzU0-1) will be displayed on both the study groups overview page and the study groups search page. This issue involves implementing the chat message component in the `src/components/widgets` directory. The data for the message, username, avatar, etc., will be fetched on the actual pages and passed to this component as props. This issue does not involve fetching data from our Supabase database but should ensure the component can receive data as props. Four different variants should be implemented, as shown in the [Figma file](https://www.figma.com/design/uP10Fb7SRKo1R1wOTEPLcd/Chat-Widget?node-id=0-1&t=sVG4VXBH5Fn8jzU0-1).

## Tasks
- Initialize a new file in the `src/components/widgets` directory.
- Create the chat message component as specified in our [Figma design](https://www.figma.com/design/uP10Fb7SRKo1R1wOTEPLcd/Chat-Widget?node-id=0-1&t=sVG4VXBH5Fn8jzU0-1).
- Implement the four different variants of the chat message component.
- Ensure that the page where the component is implemented can determine which variant is shown.

## Considerations
- Follow the design in our [Figma file](https://www.figma.com/design/uP10Fb7SRKo1R1wOTEPLcd/Chat-Widget?node-id=0-1&t=sVG4VXBH5Fn8jzU0-1) closely, including colors, padding, font sizes, margins, etc. All styling should use Tailwind CSS.
- Use variables defined in `tailwind.config.ts` instead of hard-coded values wherever possible.
- Follow best practices and ensure proper documentation.
- Integrate base components from the `src/components/ui` directory when reasonable.

**Comment by zaibutcooler** [comment]
will work on this issue

**Comment by career-tokens** [comment]
working on it

**Comment by career-tokens** [comment]
can you pls close this?
as far as I remember I had raised a pr and it was merged
