### ISSUE TITLE
Frontend > Widgets > Create Folder Widget

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#476]
## Description
The [folder widget](https://www.figma.com/design/HZPTJCQams8ocdBN8YsXjQ/Folder-Widget?node-id=0-1&t=jEyrGHLroYhW2b95-1) will be displayed on both the study group overview page and the study group materials page. This issue involves implementing the folder component in the `src/components/widgets` directory. The data for the name and date will be fetched on the actual pages and passed to this component as props. This issue does not involve fetching data from our Supabase database but should ensure the component can receive data as props. Different variants should be implemented with changes on hover, as shown in the [Figma file](https://www.figma.com/design/HZPTJCQams8ocdBN8YsXjQ/Folder-Widget?node-id=0-1&t=jEyrGHLroYhW2b95-1).

## Tasks
- Initialize a new file in the `src/components/widgets` directory.
- Create the folder component as specified in our [Figma design](https://www.figma.com/design/HZPTJCQams8ocdBN8YsXjQ/Folder-Widget?node-id=0-1&t=jEyrGHLroYhW2b95-1).
- Implement the different variants of the folder component and the specified changes on hover.
- Ensure that the page where the component is implemented can determine which variant is shown.

## Considerations
- Follow the design in our [Figma file](https://www.figma.com/design/HZPTJCQams8ocdBN8YsXjQ/Folder-Widget?node-id=0-1&t=jEyrGHLroYhW2b95-1) closely, including colors, padding, font sizes, margins, etc. All styling should use Tailwind CSS.
- Use variables defined in `tailwind.config.ts` instead of hard-coded values wherever possible.
- Follow best practices and ensure proper documentation.
- Integrate base components from the `src/components/ui` directory when reasonable.

**Comment by career-tokens** [comment]
i am doing this
