### ISSUE TITLE
Frontend > Widgets > Create Pagination Widget

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#477]
## Description
The [pagination navigation component](https://www.figma.com/design/573QnFhuclEgfof7ZG9NKl/Pagination-Widget?node-id=0-1&t=JHWmEeKSmfRb9dPV-1) will be displayed on various pages to allow users to navigate through different content on the same page. This issue involves implementing the pagination component in the `src/components/widgets` directory. The current page and total pages will be managed by the parent component and passed to this component as props. The pagination component should handle the logic for navigating between different sections of content on the same page. 

## Tasks
- Initialize a new file in the `src/components/widgets` directory.
- Create the pagination component exactly as specified in [our design](https://www.figma.com/design/573QnFhuclEgfof7ZG9NKl/Pagination-Widget?node-id=0-1&t=JHWmEeKSmfRb9dPV-1).
- Implement the navigation logic to update the current page when arrows are clicked.
Ensure that the parent component can manage and pass the current page and total pages as props to the pagination component.
- Ensure that the parent component can display the content corresponding to the current page number, which is tracked by the pagination component.
- Ensure the component is visually consistent with our design, including changes on hover and disabled states for navigation buttons.

## Considerations
- Follow the design in our [Figma file](https://www.figma.com/design/573QnFhuclEgfof7ZG9NKl/Pagination-Widget?node-id=0-1&t=JHWmEeKSmfRb9dPV-1) closely, including colors, padding, font sizes, margins, etc. All styling should use Tailwind CSS.
- Use variables defined in tailwind.config.ts instead of hard-coded values wherever possible.
- Follow best practices and ensure proper documentation.
- Integrate base components from the `src/components/ui` directory when reasonable.

**Comment by career-tokens** [comment]
i can work on this issue
