### ISSUE TITLE
Frontend > Widgets > Create Notification Card Widget

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#494]
## Description
[Notification cards](https://www.figma.com/design/f7DDsNcrvIjTdx7K7GSSh9/Notification-Card?node-id=0-1&t=oSVVs3V0tucc6NbZ-1) should be displayed both on the dashboard page and as popups. There are three types of notification cards: platform updates, group questions, and group materials. Additionally, there will be narrow and wide notification card variants. These variants are defined in the [Figma file](https://www.figma.com/design/f7DDsNcrvIjTdx7K7GSSh9/Notification-Card?node-id=0-1&t=oSVVs3V0tucc6NbZ-1). The component should be flexible enough to determine the appropriate variant based on the context in which it is used.

The implementation should be placed in a new `src/components/widgets` directory. The data for the title, content, username, date, etc., will be fetched on the actual pages and passed to this component as props. This issue does not involve fetching data from our Supabase database but should ensure the component can receive data as props.

## Tasks
- Initialize a new file in the `src/components/widgets` directory.
- Create the notification card widget as specified in our [Figma design](https://www.figma.com/design/f7DDsNcrvIjTdx7K7GSSh9/Notification-Card?node-id=0-1&t=oSVVs3V0tucc6NbZ-1).
- Implement all design variants, ensuring that the variant to display can be determined by the page context.

## Considerations
- Follow the design in our [Figma file](https://www.figma.com/design/f7DDsNcrvIjTdx7K7GSSh9/Notification-Card?node-id=0-1&t=oSVVs3V0tucc6NbZ-1) closely, including colors, padding, font sizes, margins, etc. All styling should use Tailwind CSS.
- Use variables defined in `tailwind.config.ts` instead of hard-coded values wherever possible.
- Follow best practices and ensure proper documentation.
- Integrate base components, such as buttons, from the `src/components/ui` directory when appropriate.

**Comment by career-tokens** [comment]
taking this up
