### ISSUE TITLE
Frontend > Widgets > Create Dropdown Widget

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#495]
## Description
The [dropdown widget](https://www.figma.com/design/qpxo5eUQhxW6FZzDJqJmFK/Dropdown-Widget?node-id=0-1&t=9mxnIsPnJpTrA0bO-1) will be displayed in multiple popups. This issue involves implementing the dropdown widget and ensuring it has an interactive design, including unselected, hovered, and selected states, as specified in the [Figma file](https://www.figma.com/design/qpxo5eUQhxW6FZzDJqJmFK/Dropdown-Widget?node-id=0-1&t=9mxnIsPnJpTrA0bO-1).

The implementation should be placed in a new `src/components/widgets` directory. The data for the prompt and options will be fetched on the actual pages and passed to this component as props. This issue does not involve fetching data from our Supabase database, but it should ensure that the component can receive data as props. It should also ensure that the dropdown component can handle a variable number of options.

## Tasks
- Initialize a new file in the `src/components/widgets` directory.
- Create the dropdown component as specified in our [Figma design](https://www.figma.com/design/qpxo5eUQhxW6FZzDJqJmFK/Dropdown-Widget?node-id=0-1&t=9mxnIsPnJpTrA0bO-1).

## Considerations
- Follow the design in our [Figma file](https://www.figma.com/design/qpxo5eUQhxW6FZzDJqJmFK/Dropdown-Widget?node-id=0-1&t=9mxnIsPnJpTrA0bO-1) closely, including colors, padding, font sizes, margins, etc. All styling should use Tailwind CSS.
- Use variables defined in `tailwind.config.ts` instead of hard-coded values wherever possible.
- Follow best practices and ensure proper documentation.
- Integrate base components from the `src/components/ui` directory when appropriate.

**Comment by career-tokens** [comment]
taking this up
