### ISSUE TITLE
Frontend > Update Tailwind Color Variables

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#499]
## Description
Our current `tailwind.config.ts` file is missing several important color variables necessary for our platform. We need to update this file to include the required color variables, such as shades of gray and shades of blue. Please implement all variables from the [Zeplin project](https://app.zeplin.io/project/6619c41abd3195a6618177f6) that have not yet been defined in `tailwind.config.ts`.
## Tasks
- Review the color variables defined in the [Zeplin project](https://app.zeplin.io/project/6619c41abd3195a6618177f6).
- Update the `tailwind.config.ts` file to include all these color variables.
- Ensure that the current code of the core platform uses these variables instead of hard-coded values.
## Considerations
- Follow best practices for configuring Tailwind CSS.
- Use clear and consistent naming conventions for the variables.
- Test the updated configuration to ensure it works as expected across different components and does not impact the design of our homepage.

**Comment by nikolas-source** [comment]
I'll do it
