### ISSUE TITLE
Remove Settings Route

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#507]
## Description
As we don't have many settings in our [first version](https://www.figma.com/design/1Z1NIZIPE7TTqQXM7xk8av/StudyCrew-Prototype?node-id=0-1&t=TlCTNgVhohyfyyGI-1), the settings will be shown on the user profile page. We can thereby remove the settings route from our `(core)` directory and remove the settings icon from the navbar.
## Tasks
1. Remove the settings icon from the Navbar (as defined in `/src/layout/Navbar.tsx`). This change is illustrated in this [Figma file](https://www.figma.com/design/25jNyEamdyR9IhJeVDOiVU/Navbar-Edit?node-id=0-1&t=dlx5KSxyMvC8S4y5-1), please follow the design closely.
2. Remove the `settings` folder from the `/src/app/(core)` directory.

**Comment by zaibutcooler** [comment]
will work on the issue
