### ISSUE TITLE
Study Groups > Implement Secondary Desktop Navbar

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#510]
## Description
We need to implement a secondary navbar for each study group on our platform, located next to the main navbar. This navbar will include the options "Overview," "Q&A," "Chats," and "Materials," as detailed in this [Figma file](https://www.figma.com/design/fN8DRQmsIZ2zUQAfl559mL/Study-Groups-Secondary-Navbar?node-id=0-1&t=kJC40VljkSFH73v0-1).

### Requirements:
- Follow the Figma design exactly, including color variables, fonts, and padding.
- Use Tailwind variables whenever possible instead of hardcoded values.
- Ensure the navbar navigates to all the planned page routes.
- Icons from [Phosphor Icons](https://phosphoricons.com/) should be displayed in regular tone by default and in duotone when selected.
- The secondary navbar should be implemented in the `src/components/layout` directory.
- It should only be displayed on individual study group pages, not on the general page for searching through study groups.

## Tasks
- Review the secondary navbar design in our [Figma file](https://www.figma.com/design/fN8DRQmsIZ2zUQAfl559mL/Study-Groups-Secondary-Navbar?node-id=0-1&t=kJC40VljkSFH73v0-1).
- Create the navbar component based on the design, ensuring it matches the specifications exactly.
- Ensure proper functionality, including navigation to the corresponding page routes.

**Comment by nikolas-source** [comment]
I will work on it

**Comment by Ve2s4** [comment]
Hi can take this up !

**Comment by JacobHeldt** [comment]
Awesome, thank you @Ve2s4!
