### ISSUE TITLE
Frontend > Pages > Create Search Groups Page

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#513]
## Description
We are ready to begin implementing the [Search Groups Page](https://www.figma.com/design/dRFAHmjtgsp1yx2LpIEJCN/Search-Groups-Page?node-id=0-1&t=sUh5oYe7Fh3YifsE-1) on the `/groups` route. The necessary components are available in the `src/components` directory.

This page will be displayed when a user clicks on the primary group icon in the navbar, but **not** when clicking on an individual group icon. The task involves:
- Creating the page layout.
- Fetching the appropriate data from our Supabase mock database.
- Ensuring the page functions correctly.

### Key Elements
- **Group Cards and Filter Tags:** Use components from the `src/components/widgets` directory.
- **Group Carousel:** Display all groups the user is part of.
- **Other Groups Section:** Rank groups by their number of members.
- **Filter Functionality:** Clicking a filter tag should filter group cards by subject.
- **Navbar and Header:** Integrate from `src/components/layout`.
- **Search Bars:** Implement as white boxes without functionality for now (functionality to be added later).

### Note
The create group popup will be addressed in a separate issue.

## Tasks
- Implement the Search Groups Page layout as defined in the [Figma file](https://www.figma.com/design/dRFAHmjtgsp1yx2LpIEJCN/Search-Groups-Page?node-id=0-1&t=sUh5oYe7Fh3YifsE-1).
- Display the logged-in user's data accurately.
- Ensure the page functions correctly and matches the Figma design in terms of interactivity.

## Considerations
- Follow the design specifications in the [Figma file](https://www.figma.com/design/dRFAHmjtgsp1yx2LpIEJCN/Search-Groups-Page?node-id=0-1&t=sUh5oYe7Fh3YifsE-1), including fonts, colors, and padding.
- Use variables from `tailwind.config.ts` to avoid hard-coded values.
- Integrate UI components and widgets from the `src/components` directory wherever appropriate.
- Adhere to best practices and ensure proper documentation.

**Comment by franclobo** [comment]
I'll work on this.

**Comment by JacobHeldt** [comment]
Awesome, thank you @franclobo!
