### ISSUE TITLE
Frontend > Pages > User Profile Page

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#524]
## Description
We are ready to begin implementing the [User Profile Page](https://www.figma.com/design/KgREO9j4x0sI6dJtOxJQo5/User-Profile-Page?node-id=0-1&t=QrUxyrDcCMcQSg0Q-1) on the `/profile` route. The necessary components are available in the `src/components` directory.

This page will be displayed when a user clicks on the user icon at the bottom of the navbar. This issue involves creating the page layout and fetching the appropriate data from our mock database. The functionality of specific buttons and editing properties will be addressed in separate issues.

## Key Elements
- **Profile Section**: Includes user avatar, username, and an "about" section.
- **Account Section**: Contains fields for editing emails and toggles for different settings. The toggles should be displayed and clickable, but they do not need to update the properties in the Supabase mock database yet. The same applies to buttons.

## Tasks
- Implement the profile page layout as defined in the [Figma file](https://www.figma.com/design/KgREO9j4x0sI6dJtOxJQo5/User-Profile-Page?node-id=1-410&t=thnWZEl1Cbi6SOfo-1).
- Accurately display the logged-in user's data.

## Considerations
- Follow the design specifications in the [Figma file](https://www.figma.com/design/KgREO9j4x0sI6dJtOxJQo5/User-Profile-Page?node-id=1-410&t=thnWZEl1Cbi6SOfo-1) closely, including fonts, colors, and padding.
- Use variables from `tailwind.config.ts` to avoid hard-coded values.
- Integrate UI components and widgets from the `src/components` directory wherever appropriate.
- Adhere to best practices and ensure proper documentation.

**Comment by jlescalonap** [comment]
@JacobHeldt count on me for this one please!

**Comment by franclobo** [comment]
Ok, @jlescalonap I assigned you. Please follow the instructions in the CONTRIBUTING.md file to contribute.
