### ISSUE TITLE
Social Login (OAuth) Signin with Google

### ISSUE THREAD

**Issue by franclobo** [StudyCrew/StudyCrew#535]
**Description**

Supabase Auth supports Sign in with Google for the web, native Android applications, and Chrome extensions.

**Prerequisites**

A Google Cloud project. Go to the [Google Cloud Platform](https://console.cloud.google.com/home/dashboard) and create a new project if necessary.

**Configuration**

All the process is described on the Supabase [documentation](https://supabase.com/docs/guides/auth/social-login/auth-google?queryGroups=platform&platform=web)
Activities

- Create the project in Google Cloud Platform.
- Set up the signin button.

**Comment by Ve2s4** [comment]
I want to work on it, I have implemented it before using supabase.

**Comment by Ve2s4** [comment]
Sure thing.
