### ISSUE TITLE
User Profile Button in Navbar Navigates to Wrong Route

### ISSUE THREAD

**Issue by JacobHeldt** [StudyCrew/StudyCrew#572]
## Describe the Bug
When a user clicks on the user icon in the navbar, they are navigated to the /profile/[profile_id] route, as shown in the screenshot below: <img width="1223" alt="Screenshot 2024-09-22 at 3 52 43 PM" src="https://github.com/user-attachments/assets/d83864eb-1cad-4ee3-bb44-fb0ce74c2ed1">

## To Reproduce
1. Log in to the platform.
2. Click on the user icon at the bottom of the navbar.
3. Examine the URL.

## Expected Behavior
The user icon in the navbar should navigate to the /profile route instead of the /profile/[profile_id] route.

**Comment by franclobo** [comment]
I got it. I will fix it now.
