### ISSUE TITLE
FEAT: Create Issue forms

### ISSUE THREAD

**Issue by dakshsinghrathore** [StudyCrew/StudyCrew#579]
**Is your feature request related to a problem? Please describe.**
I want to enhance the issue buttons feature by allowing users to fill out a form for specific issues. This will not only make the process visually appealing but also streamline the experience for contributors when raising an issue. Here’s an example of what a Bug Issue Form could look like: 👇
**Describe the solution you'd like**

![Screenshot 2023-06-11 at 01-15-06 New Issue · dakshsinghrathore_htmltut](https://github.com/MonalikaPatnaik/UMatter/assets/115932772/d6d11ddf-3874-4229-b9a8-6087c99e10e2)

**Describe alternatives you've considered**
**NIL**

**Additional context**
Will replace the md files of the respective issue buttons with their yml counterparts which would enable this feature.
**REF** : [Doc for Issue form]( https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

**Comment by dakshsinghrathore** [comment]
@JacobHeldt I'm excited to work on this issue! Should I go ahead and raise the PR?

**Comment by JacobHeldt** [comment]
Sure, sounds great @dakshsinghrathore!
