### ISSUE TITLE
Layout > Home page > Mobile > Feature cards have margin

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#79]
## Is your feature request related to a problem? Please describe.
When viewing the home page on a mobile device, there is an margin on the feature cards that causes them to be very narrow.

## Describe the solution you'd like
Adjust the layout and styling of the mobile responsive site to make the feature cards take up the full available width. A look similar to this is desired: 
![image](https://github.com/StudyCrew/StudyCrew/assets/105601287/60186e91-3592-48f9-9a35-3fe9c2d2095f)

## Screenshots
This is the current, unresponsive look.
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/d87792f1-631e-437e-b5bd-7671f2b50f96)

**Comment by Kingrashy12** [comment]
I would like to work on this issue

**Comment by kylescudder** [comment]
Hi @Kingrashy12 any chance of this being done before the end of the year?

**Comment by kylescudder** [comment]
Closing now as it has been addressed by another ticket.
