### ISSUE TITLE
Layout > Home page > Mobile > Incorrect footer spacing 

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#80]
## Is your feature request related to a problem? Please describe.
When viewing the home page on a mobile device, the footer spacing is incorrect and inconsistent. 

## Describe the solution you'd like
Adjust the layout and styling of the mobile responsive site to correct the footer spacing/margin.

## Screenshots
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/807dfb57-e474-43fe-b6f9-c24a69167481)

**Comment by Kingrashy12** [comment]
I would like to work on this issue
