### ISSUE TITLE
Styling > Home page > Mission icons replaced with single SVG

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#85]
## Is your feature request related to a problem? Please describe.
The position of the mission SVGs change a lot with different screen sizes and on some screen sizes, not all logos are shown.

## Describe the solution you'd like
Replaced the 3 separate SVGs with a single SVG containing all three icons. This will help them maintain their relative position on all device sizes.
Once the new icons in place, the mission section should have a 50/50 split of the width of desktop devices.
This should behave reasonably and responsively on all device sizes.

## Screenshots

Desired design
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/d68034c7-d906-4e87-9520-d1b42d7edaeb)

## Additional Information
Please get the SVG from Figma document, or message @JacobHeldt or @kylescudder

**Comment by Kingrashy12** [comment]
I would like to work on this issue

**Comment by JacobHeldt** [comment]
> I would like to work on this issue 

Thank you, I will assing the issue to you and send you the necessary files.

**Comment by kylescudder** [comment]
Hi @Kingrashy12, I am not sure how far you have made it on this request, but as you may have seen from the branch created, I have already started on the work for this. 
Ignore the margin on the right, this is a known issue and there is an active issue for it.

Desktop:
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/91e3d13b-cf29-4ea5-8b1a-b1054114bf25)

Mobile:
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/a856966e-7840-42c5-8fe7-e3f53f76334c)

@JacobHeldt mine is ready for PR I just didn't get a chance to submit before Christmas. What would you like me to do with it?
