### ISSUE TITLE
Styling > Home page > Correct footer horizontal margin

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#86]
## Is your feature request related to a problem? Please describe.
The footer content margin does not match what is required in the design brief. 

## Describe the solution you'd like
Adjust the content in the footer to have a horizontal margin of 150px.

## Screenshots

Footer
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/1e52cb78-a4db-4bff-9435-b53c76a77f5b)

**Comment by Kingrashy12** [comment]
I would like to work on this issue
