### ISSUE TITLE
Styling > Home page > Mission section > Title and description overlap when device dimensions are smaller

### ISSUE THREAD

**Issue by kylescudder** [StudyCrew/StudyCrew#88]
## Is your feature request related to a problem? Please describe.
On different sized devices, the mission title and description sometimes overlap, depending on the device size.

## Describe the solution you'd like
Move these items into rows that do now overlap, preferably using the grid system in tailwindcss.

## Screenshots

Mission title and description on narrow device
![image](https://github.com/StudyCrew/StudyCrew/assets/74150974/6a00a8e7-c05a-4611-82df-bf3d9a107b84)

**Comment by vishalbhati123** [comment]
Hey Kyle, is it possible to know the screen width where this occurs, I am guessing this could be for responsive for tablets, and smaller laptops.

**Comment by kylescudder** [comment]
Hi @vishalbhati123 thanks for brining this to my attention, I believe there is quite a lot of overlap between this issue, #85 and #35. As you can see from the branch #85 I have already started on this area, so if you could find an issue that does not overlap with these ticket, I would appreciate that, otherwise merging will become a problem later on.

**Comment by kylescudder** [comment]
Just as I thought, this was resolved by #85. Closing now.
